version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Django app's Dockerfile
    expose:
      - 8000  # Expose the port on which Gunicorn is running
    environment:
      - DJANGO_SETTINGS_MODULE=vamt_api.settings.prod
    networks:
      - web-network

  nginx:
    image: nginx:latest
    ports:
      - 80:80  # Map Nginx port 80 to host port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Path to your Nginx configuration file
      - ./nginx/conf.d:/etc/nginx/conf.d  # Path to your Nginx site configuration directory
    depends_on:
      - django
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
  