# Generated by Django 4.2.3 on 2023-07-13 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('type', models.CharField(choices=[('civil', 'Civil'), ('criminal', 'Criminal')], db_index=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grad_year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('side_constrained', models.BooleanField(default=None)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.case')),
            ],
        ),
        migrations.CreateModel(
            name='WitnessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='WitnessRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('P', 'P'), ('D', 'D')], db_index=True, max_length=1)),
                ('attorney', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attorney', to='reference.competitor')),
                ('portrayed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portrayed_by', to='reference.competitor')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.witness')),
            ],
        ),
        migrations.AddField(
            model_name='witness',
            name='types',
            field=models.ManyToManyField(to='reference.witnesstype'),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.case')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_closer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_close', to='reference.competitor')),
                ('d_opener', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='d_open', to='reference.competitor')),
                ('dw_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dw_1', to='reference.witnessrole')),
                ('dw_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dw_2', to='reference.witnessrole')),
                ('dw_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dw_3', to='reference.witnessrole')),
                ('p_closer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_close', to='reference.competitor')),
                ('p_opener', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_open', to='reference.competitor')),
                ('pw_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pw_1', to='reference.witnessrole')),
                ('pw_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pw_2', to='reference.witnessrole')),
                ('pw_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pw_3', to='reference.witnessrole')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.tournament')),
            ],
        ),
    ]
